spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/timetracker
    username: timetracker
    password: timetracker123
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.cdek.tasktimetracker.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html